package com.kai.time.bean

data class HotBean(var bImg: String,
                   var date: String,
                   var hasPromo: Boolean,
                   var lid: Int,
                   var newActivitiesTime: Int,
                   var promo: Promo,
                   var totalComingMovie: Int,
                   var voucherMsg: String,
                   var ms: List<Ms>) {
    data class Promo(val id: Int)
    data class Ms(var NearestCinemaCount: Int,
                  var NearestDay: Int,
                  var NearestShowtimeCount: Int,
                  var aN1: String,
                  var aN2: String,
                  var actors: String,
                  var cC: Int,
                  var commonSpecial: String,
                  var d: String,
                  var dN: String,
                  var def: Int,
                  var id: Int,
                  var img: String,
                  var is3D: Boolean,
                  var isDMAX: Boolean,
                  var isFilter: Boolean,
                  var isHasTrailer: Boolean,
                  var isHot: Boolean,
                  var isIMAX: Boolean,
                  var isIMAX3D: Boolean,
                  var isNew: Boolean,
                  var isTicket: Boolean,
                  var m: String,
                  var movieType: String,
                  var preferentialFlag: Boolean,
                  var r: Double,
                  var rc: Int,
                  var rd: String,
                  var rsC: Int,
                  var sC: Int,
                  var t: String,
                  var tCn: String,
                  var tEn: String,
                  var ua: Int,
                  var wantedCount: Int,
                  var year: String,
                  var p: List<String>,
                  var versions: List<Versions>) {
        data class Versions(var `enum`: Int,
                            var version: String)
    }
}